export const links = [
    {
        name: "Home",
        hash: "#home",
    },
    {
        name: "Creator",
        hash: "#creator",
    },
    {
        name: "Dreams",
        hash: "#dreams",
    },
    {
        name: "Fund",
        hash: "#fund",
    },
    {
        name: "Lottery",
        hash: "#lottery",
    },
] as const

export const creatorInputs = [
    { type: "text", name: "goal", placeholder: "Goal (ETH)" },
    { type: "text", name: "expiration", placeholder: "Expiration (Days)" },
    { type: "text", name: "wallet", placeholder: "Wallet For Withdrawals" },
] as const

export const dreamsData = [
    {
        creator: "John Doe",
        designatedWallet: "0x1234...5678",
        totalGathered: 500,
        goal: 1000,
        id: "1",
        status: "Ongoing",
        description: "Lorem ipsum dolor sit amet...",
        timeLeftToExpiration: "2 days left",
        promoted: true,
    },
    {
        creator: "John Doe",
        designatedWallet: "0x1234...5678",
        totalGathered: 500,
        goal: 1000,
        id: "2",
        status: "Ongoing",
        description: "Lorem ipsum dolor sit amet...",
        timeLeftToExpiration: "2 days left",
        promoted: true,
    },
    {
        creator: "John Doe",
        designatedWallet: "0x1234...5678",
        totalGathered: 500,
        goal: 1000,
        id: "3",
        status: "Ongoing",
        description: "Lorem ipsum dolor sit amet...",
        timeLeftToExpiration: "2 days left",
        promoted: true,
    },
    {
        creator: "John Doe",
        designatedWallet: "0x1234...5678",
        totalGathered: 500,
        goal: 1000,
        id: "4",
        status: "Ongoing",
        description: "Lorem ipsum dolor sit amet...",
        timeLeftToExpiration: "2 days left",
        promoted: true,
    },
    {
        creator: "John Doe",
        designatedWallet: "0x1234...5678",
        totalGathered: 500,
        goal: 1000,
        id: "5",
        status: "Ongoing",
        description: "Lorem ipsum dolor sit amet...",
        timeLeftToExpiration: "2 days left",
        promoted: true,
    },
    {
        creator: "John Doe",
        designatedWallet: "0x1234...5678",
        totalGathered: 500,
        goal: 1000,
        id: "6",
        status: "Ongoing",
        description: "Lorem ipsum dolor sit amet...",
        timeLeftToExpiration: "2 days left",
        promoted: true,
    },
    {
        creator: "John Doe",
        designatedWallet: "0x1234...5678",
        totalGathered: 500,
        goal: 1000,
        id: "7",
        status: "Ongoing",
        description: "Lorem ipsum dolor sit amet...",
        timeLeftToExpiration: "2 days left",
        promoted: true,
    },
    {
        creator: "John Doe",
        designatedWallet: "0x1234...5678",
        totalGathered: 500,
        goal: 1000,
        id: "8",
        status: "Ongoing",
        description: "Lorem ipsum dolor sit amet...",
        timeLeftToExpiration: "2 days left",
        promoted: true,
    },
    {
        creator: "John Doe",
        designatedWallet: "0x1234...5678",
        totalGathered: 500,
        goal: 1000,
        id: "9",
        status: "Ongoing",
        description: "Lorem ipsum dolor sit amet...",
        timeLeftToExpiration: "2 days left",
        promoted: true,
    },
    {
        creator: "John Doe",
        designatedWallet: "0x1234...5678",
        totalGathered: 500,
        goal: 1000,
        id: "10",
        status: "Ongoing",
        description: "Lorem ipsum dolor sit amet...",
        timeLeftToExpiration: "2 days left",
        promoted: true,
    },
] as const
